#!/usr/bin/env bash
# Local hourly poller — pulls R3090 Phase-1 autopilot artifacts to local
# docs/tmp/r3090_phase1_snapshot/. Designed to be triggered by Windows Task
# Scheduler via:
#   wsl bash /mnt/c/source/JDCNET/ops/local_r3090_poll.sh
#
# Outputs:
#   docs/tmp/r3090_phase1_snapshot/<UTC_YYYYMMDD_HHMMSS>/   # one snapshot per call
#   docs/tmp/r3090_phase1_snapshot/latest/                  # symlink to newest
#   docs/tmp/r3090_phase1_snapshot/poll.log                 # append-only audit
#   docs/tmp/r3090_phase1_snapshot/FINAL_SUMMARY.md         # written when AUTOPILOT_DONE seen
#
# Idempotent: if AUTOPILOT_DONE is already mirrored locally we still snapshot
# the timestamped GPU/log state (cheap) but skip writing FINAL_SUMMARY twice.

set -u
ROOT=/mnt/c/source/JDCNET
SNAP_DIR=$ROOT/src/tmp_sync/r3090_phase1_snapshot
LOG=$SNAP_DIR/poll.log
mkdir -p "$SNAP_DIR"

ts=$(date -u '+%Y%m%dT%H%M%SZ')
out=$SNAP_DIR/$ts
mkdir -p "$out"

log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*" >> "$LOG"; }

# Read R3090 credentials from /mnt/c/source/.env (lines:
#   mabo1215@10.147.20.176
#   mabo1215
# )
ENV_FILE=/mnt/c/source/.env
if [ ! -f "$ENV_FILE" ]; then
    log "ENV_FILE_MISSING: $ENV_FILE"; exit 2
fi
HOST=$(grep -oE 'mabo1215@10\.147\.20\.176' "$ENV_FILE" | head -1)
PWD_LINE=$(awk '/mabo1215@10\.147\.20\.176/{getline; print; exit}' "$ENV_FILE")
if [ -z "$HOST" ] || [ -z "$PWD_LINE" ]; then
    log "ENV_PARSE_FAILED host=[$HOST] pwd_len=${#PWD_LINE}"; exit 2
fi

ssh_run() {
    sshpass -p "$PWD_LINE" ssh -o ConnectTimeout=20 -o BatchMode=no \
        -o StrictHostKeyChecking=accept-new -o LogLevel=ERROR \
        "$HOST" "$@"
}
ssh_pull() {
    # ssh_pull <remote_glob> <local_dest_dir>
    local remote=$1 dest=$2
    sshpass -p "$PWD_LINE" scp -q -o ConnectTimeout=20 \
        -o StrictHostKeyChecking=accept-new -o LogLevel=ERROR \
        -r "$HOST:$remote" "$dest" 2>>"$LOG" || true
}

log "==== POLL_BEGIN ts=$ts ===="

# 1) GPU + process snapshot
ssh_run 'echo ===NVIDIA_SMI===; nvidia-smi --query-gpu=index,utilization.gpu,memory.used,memory.total --format=csv,noheader,nounits 2>/dev/null;
echo ===COMPUTE_APPS===; for i in 0 1 2 3; do echo "GPU $i: $(nvidia-smi -i $i --query-compute-apps=pid --format=csv,noheader 2>/dev/null | tr "\n" "," | sed "s/,$//")"; done;
echo ===PROCS===; pgrep -af "bimcv_resnet18" | grep python | grep -v grep;
echo ===QUEUE===; cat /data/JDCNET/job_pool/phase1_queue.txt 2>/dev/null;
echo ===AUTOPILOT_LOG_TAIL===; tail -n 80 /data/logs/phase1_autopilot/autopilot.log 2>/dev/null;
echo ===LAUNCHES_LOG_TAIL===; tail -n 80 /data/logs/phase1_autopilot/launches.log 2>/dev/null;
echo ===DONE_MARKER===; cat /data/logs/phase1_autopilot/AUTOPILOT_DONE 2>/dev/null
' > "$out/snapshot.txt" 2>>"$LOG"

# 2) Best metrics + history.csv per run dir
mkdir -p "$out/runs"
ssh_pull '/data/JDCNET/src/runs/bimcv_phase1_diag/*/best_metrics.json' "$out/runs/"
ssh_pull '/data/JDCNET/src/runs/bimcv_phase1_diag/*/history.csv' "$out/runs/"

# Note: scp -r above works because remote glob expands to multiple files,
# all of which are copied flat into $out/runs/. To preserve naming, use a
# directory listing pull instead:
ssh_run 'cd /data/JDCNET/src/runs/bimcv_phase1_diag 2>/dev/null && for d in */; do
    name=${d%/}
    if [ -f "$name/best_metrics.json" ]; then
        echo "===BEST $name==="; cat "$name/best_metrics.json"
    fi
done' > "$out/best_metrics_concat.txt" 2>>"$LOG"

# 3) Resampling outputs if present
ssh_pull '/data/logs/phase1_autopilot/resampling_summary.csv' "$out/" 2>/dev/null
ssh_pull '/data/logs/phase1_autopilot/resampling_wilcoxon.txt' "$out/" 2>/dev/null
ssh_pull '/data/logs/phase1_autopilot/resample_eval.log' "$out/" 2>/dev/null

# 4) Update "latest" pointer
rm -rf "$SNAP_DIR/latest"
ln -snf "$out" "$SNAP_DIR/latest" 2>>"$LOG" || cp -r "$out" "$SNAP_DIR/latest"

# 5) AUTOPILOT_DONE detection — query the remote marker file directly so we
#    don't false-positive on the header line "===DONE_MARKER===" itself.
done_marker_remote_present=$(ssh_run 'cat /data/logs/phase1_autopilot/AUTOPILOT_DONE 2>/dev/null' 2>/dev/null | tr -d '[:space:]')
final_summary=$SNAP_DIR/FINAL_SUMMARY.md
if [ -n "$done_marker_remote_present" ] && [ ! -f "$final_summary.locked" ]; then
    log "AUTOPILOT_DONE detected (remote_ts=$done_marker_remote_present); writing FINAL_SUMMARY.md"
    {
        echo "# Phase-1 Autopilot — Final Summary"
        echo ""
        echo "Generated by local poller at $(date -u '+%Y-%m-%dT%H:%M:%SZ')."
        echo "Remote AUTOPILOT_DONE timestamp: ${done_marker_remote_present}"
        echo ""
        echo "## Best metrics per run"
        echo ""
        echo '```'
        cat "$out/best_metrics_concat.txt" 2>/dev/null
        echo '```'
        echo ""
        echo "## Resampling Wilcoxon"
        echo ""
        echo '```'
        cat "$out/resampling_wilcoxon.txt" 2>/dev/null || echo "(file missing)"
        echo '```'
        echo ""
        echo "## Per-resample table head"
        echo ""
        echo '```'
        head -40 "$out/resampling_summary.csv" 2>/dev/null || echo "(file missing)"
        echo '```'
    } > "$final_summary"
    touch "$final_summary.locked"
    log "FINAL_SUMMARY.md written."
fi

# 6) Compact poll.log entry
nrun=$(ls "$out/runs/" 2>/dev/null | grep -c best_metrics.json || true)
queue_remaining=$(grep -A100 '===QUEUE===' "$out/snapshot.txt" 2>/dev/null | tail -n +2 | sed -n '/^===/,$d;p' | grep -c bimcv_resnet18 || true)
running=$(grep -A100 '===PROCS===' "$out/snapshot.txt" 2>/dev/null | tail -n +2 | sed -n '/^===/,$d;p' | grep -c bimcv_resnet18 || true)
log "POLL_END best_metrics_pulled=$nrun queue_remaining=$queue_remaining running=$running done_marker_seen=${done_marker_remote_present:-no}"

# Keep snapshot history bounded — retain last 24
ls -dt "$SNAP_DIR"/[0-9]*Z 2>/dev/null | tail -n +25 | xargs -r rm -rf

exit 0
