#!/usr/bin/env bash
set -euo pipefail
# DRR extended seeds 45-47 for Exp1 (DRR teacher 5-fold)
# 3 rows (teacher, supervised, gated_kd) x 5 folds x 3 seeds = 45 runs
# Uses same TAG/RUN_ROOT as main experiment; done_run() skips completed runs

ROOT=${ROOT:-/data/JDCNET_git/src}
PYTHON_BIN=${PYTHON_BIN:-python3}
CV_DIR=${CV_DIR:-/data1/midrc/bimcv_only_cv_20260514}
PREFIX=${PREFIX:-bimcv_only}

TAG=${TAG:-bimcv_drr_cv_20260515}
RUN_ROOT=${RUN_ROOT:-/data1/midrc/runs/${TAG}}
CONFIG_DIR=${CONFIG_DIR:-$ROOT/configs/${TAG}}
LOG_DIR=${LOG_DIR:-/data1/logs/${TAG}}
DRR_SHM=${DRR_SHM:-/dev/shm/bimcv_drr}
DRR_SRC=${DRR_SRC:-/data/bimcv/drr_cache}
DRR_MANIFEST_DIR=${DRR_MANIFEST_DIR:-/data1/midrc/bimcv_drr_cv_20260515}

FOLDS=${FOLDS:-"0 1 2 3 4"}
SEEDS=${SEEDS:-"45 46 47"}

GPUS=${GPUS:-"0 1 2 3"}
CONCURRENCY=${CONCURRENCY:-3}
EPOCHS=${EPOCHS:-50}
INPUT_SIZE=${INPUT_SIZE:-224}
BATCH_SIZE=${BATCH_SIZE:-256}
NUM_WORKERS=${NUM_WORKERS:-1}
AMP=${AMP:-true}
CHANNELS_LAST=${CHANNELS_LAST:-true}
TORCH_COMPILE=${TORCH_COMPILE:-false}
VALIDATION_INTERVAL=${VALIDATION_INTERVAL:-1}
USE_WEIGHTED_SAMPLER=${USE_WEIGHTED_SAMPLER:-true}
ALPHA=${ALPHA:-0.6}
GATE_FLOOR=${GATE_FLOOR:-0.0}
T_DRR=${T_DRR:-4.0}
THR_DRR=${THR_DRR:-0.50}

mkdir -p "$RUN_ROOT" "$CONFIG_DIR" "$LOG_DIR" "$DRR_MANIFEST_DIR" "$DRR_SHM"

STATUS="$LOG_DIR/status_ext.tsv"
touch "$STATUS"

log() { printf '%s\t%s\n' "$(date -Is)" "$*" | tee -a "$STATUS"; }
done_run() { [ -s "$1/best_metrics.json" ] && [ -s "$1/best.pt" ]; }
done_test_eval() { [ -s "$1/test_eval/metrics.json" ]; }

log "EXT_SEEDS_START tag=$TAG seeds=[$SEEDS] gpus=[$GPUS]"

# Ensure DRR images in /dev/shm
DRR_COUNT=$(ls "$DRR_SHM"/*.png 2>/dev/null | wc -l)
if [ "$DRR_COUNT" -lt 100 ]; then
    log "COPY_DRR src=$DRR_SRC -> $DRR_SHM"
    cp "$DRR_SRC"/bimcv_S*.png "$DRR_SHM"/
    DRR_COUNT=$(ls "$DRR_SHM"/*.png | wc -l)
fi
log "DRR_IMAGES count=$DRR_COUNT"

export ROOT RUN_ROOT CONFIG_DIR CV_DIR LOG_DIR DRR_SHM DRR_MANIFEST_DIR PREFIX
export FOLDS SEEDS EPOCHS INPUT_SIZE BATCH_SIZE NUM_WORKERS AMP CHANNELS_LAST
export TORCH_COMPILE VALIDATION_INTERVAL USE_WEIGHTED_SAMPLER ALPHA GATE_FLOOR
export T_DRR THR_DRR TAG

"$PYTHON_BIN" - << 'PY'
import json, os, re
import pandas as pd
from pathlib import Path

cv_dir = Path(os.environ["CV_DIR"])
prefix = os.environ["PREFIX"]
drr_shm = Path(os.environ["DRR_SHM"])
drr_manifest_dir = Path(os.environ["DRR_MANIFEST_DIR"])
run_root = Path(os.environ["RUN_ROOT"])
config_dir = Path(os.environ["CONFIG_DIR"])
log_dir = Path(os.environ["LOG_DIR"])

folds = [int(x) for x in os.environ["FOLDS"].split()]
seeds = [int(x) for x in os.environ["SEEDS"].split()]

epochs = int(os.environ["EPOCHS"])
input_size = int(os.environ["INPUT_SIZE"])
batch_size = int(os.environ["BATCH_SIZE"])
num_workers = int(os.environ["NUM_WORKERS"])
amp = os.environ["AMP"].lower() == "true"
channels_last = os.environ["CHANNELS_LAST"].lower() == "true"
torch_compile = os.environ["TORCH_COMPILE"].lower() == "true"
val_interval = int(os.environ["VALIDATION_INTERVAL"])
weighted = os.environ["USE_WEIGHTED_SAMPLER"].lower() == "true"
alpha = float(os.environ["ALPHA"])
gate_floor = float(os.environ["GATE_FLOOR"])
t_drr = float(os.environ["T_DRR"])
thr_drr = float(os.environ["THR_DRR"])

# Load existing manifests (generated by main script)
drr_teacher_manifest_paths = {}
drr_student_manifest_paths = {}
for fold in folds:
    t_csv = drr_manifest_dir / f"drr_fold{fold:02d}_teacher_manifest.csv"
    s_csv = drr_manifest_dir / f"drr_fold{fold:02d}_student_manifest.csv"
    if not t_csv.exists() or not s_csv.exists():
        raise FileNotFoundError(f"Missing manifests for fold {fold}. Run main script first.")
    drr_teacher_manifest_paths[fold] = str(t_csv)
    drr_student_manifest_paths[fold] = str(s_csv)
    df = pd.read_csv(str(s_csv))
    print(f"  fold{fold}: teacher_manifest={t_csv.name}, student_manifest={s_csv.name}, rows={len(df)}")

base_model = {
    "name": "student", "num_classes": 2, "input_size": input_size,
    "use_dpe": False, "use_mhra": False, "use_dfpn": False, "paired_input": False,
    "backbone": "resnet18",
}

def data_cfg(modalities, batch, paired_col=None):
    d = {
        "train_split": "train", "val_split": "val",
        "train_modalities": modalities, "val_modalities": modalities,
        "batch_size": batch, "num_workers": num_workers,
        "use_weighted_sampler": weighted, "pin_memory": True,
        "persistent_workers": num_workers > 0,
        "prefetch_factor": 4 if num_workers > 0 else None,
    }
    if paired_col:
        d["paired_image_column"] = paired_col
    return d

def optim_cfg():
    return {
        "epochs": epochs,
        "learning_rate": 3e-4, "weight_decay": 1e-4,
        "grad_accum_steps": 1, "amp": amp, "channels_last": channels_last,
        "torch_compile": torch_compile, "validation_interval": val_interval,
    }

def gated_kd_dist(t, thr, teacher_ckpt):
    return {
        "enabled": True, "temperature": t, "alpha": alpha,
        "teacher_checkpoint": teacher_ckpt,
        "confidence_gate_enabled": True, "confidence_gate_threshold": thr,
        "confidence_gate_floor": gate_floor, "confidence_gate_power": 1.0,
        "confidence_gate_requires_correct": True,
        "confidence_gate_positive_threshold": -1.0,
        "confidence_gate_negative_threshold": -1.0,
        "confidence_gate_min_margin": 0.0, "confidence_gate_max_entropy": -1.0,
        "projected_attention_weight": 0.0,
    }

all_names = []  # (name, priority)

def write_cfg(name, manifest, model, data, optim, distill=None, priority=1):
    cfg = {
        "experiment_name": name,
        "manifest_path": manifest,
        "output_dir": str(run_root / name),
        "seed": int(re.search(r'_s(\d+)', name).group(1)),
        "model": model, "data": data, "optimization": optim,
        "distillation": distill or {"enabled": False},
    }
    (config_dir / f"{name}.json").write_text(json.dumps(cfg, indent=2))
    all_names.append((name, priority))

print("[ext] generating DRR ext seeds configs...")
for fold in folds:
    t_manifest = drr_teacher_manifest_paths[fold]
    s_manifest = drr_student_manifest_paths[fold]
    for seed in seeds:
        tag_fs = f"e1_f{fold:02d}_s{seed}"
        teacher_ckpt = str(run_root / f"drr_{tag_fs}_teacher" / "best.pt")

        write_cfg(f"drr_{tag_fs}_teacher", t_manifest,
                  base_model, data_cfg(["xray"], batch_size), optim_cfg(),
                  priority=0)
        write_cfg(f"drr_{tag_fs}_supervised", s_manifest,
                  base_model, data_cfg(["xray"], batch_size), optim_cfg(),
                  priority=1)
        write_cfg(f"drr_{tag_fs}_gated_kd_t{int(t_drr*10):03d}_thr{int(thr_drr*100):03d}",
                  s_manifest,
                  base_model, data_cfg(["xray"], batch_size, "teacher_image_path"),
                  optim_cfg(), gated_kd_dist(t_drr, thr_drr, teacher_ckpt), priority=2)

all_names.sort(key=lambda x: (x[1], x[0]))
names_ordered = [n for n, _ in all_names]

names_file = log_dir / "ext_seeds_names.txt"
names_file.write_text("\n".join(names_ordered) + "\n")
print(f"[done] {len(names_ordered)} configs (teachers first, then supervised, then KD)")
PY

if [ ! -s "$LOG_DIR/ext_seeds_names.txt" ]; then
  log "FATAL no configs generated"; exit 1
fi

NUM_RUNS=$(wc -l < "$LOG_DIR/ext_seeds_names.txt")
log "EXT_CONFIGS=$NUM_RUNS"

# ── Launch: 4 GPU x 3 concurrent ─────────────────────────────────────────────
mapfile -t gpu_array < <(printf '%s\n' $GPUS)
mapfile -t all_names < "$LOG_DIR/ext_seeds_names.txt"

for gpu_idx in "${!gpu_array[@]}"; do
  gpu="${gpu_array[$gpu_idx]}"
  assigned=()
  for idx in "${!all_names[@]}"; do
    if [ $((idx % ${#gpu_array[@]})) -eq "$gpu_idx" ]; then
      assigned+=("${all_names[$idx]}")
    fi
  done
  [ "${#assigned[@]}" -eq 0 ] && continue

  script="$LOG_DIR/gpu${gpu}_ext_queue.sh"
  qfile="$LOG_DIR/gpu${gpu}_ext_names.txt"
  printf '%s\n' "${assigned[@]}" > "$qfile"

  {
    echo "#!/usr/bin/env bash"
    echo "set -euo pipefail"
    echo "cd '$ROOT'"
    echo "STATUS='$STATUS'"
    echo "LOG_DIR='$LOG_DIR'"
    echo "CONFIG_DIR='$CONFIG_DIR'"
    echo "RUN_ROOT='$RUN_ROOT'"
    echo "PYTHON_BIN='$PYTHON_BIN'"
    echo "gpu=$gpu"
    echo 'log(){ printf "%s\t%s\n" "$(date -Is)" "$*" | tee -a "$STATUS"; }'
    echo 'done_run(){ [ -s "$1/best_metrics.json" ] && [ -s "$1/best.pt" ]; }'
    echo 'done_test_eval(){ [ -s "$1/test_eval/metrics.json" ]; }'
    cat << 'FUNC'
run_one(){
  local gpu=$1 name=$2
  local cfg="$CONFIG_DIR/${name}.json"
  local run_dir="$RUN_ROOT/${name}"
  local log_f="$LOG_DIR/${name}.log"
  local test_cfg="$CONFIG_DIR/${name}.test.json"
  if done_run "$run_dir"; then
    log "SKIP_DONE $name"
  else
    log "START gpu=$gpu $name"
    CUDA_VISIBLE_DEVICES=$gpu "$PYTHON_BIN" -u -m jdcnet_exp.train \
      --config "$cfg" > "$log_f" 2>&1
    log "DONE gpu=$gpu $name"
  fi
  "$PYTHON_BIN" - "$cfg" "$test_cfg" << 'PY'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
p = json.load(open(src))
p["data"] = dict(p["data"]); p["data"]["val_split"] = "test"
json.dump(p, open(dst, "w"), indent=2)
PY
  if done_test_eval "$run_dir"; then
    log "SKIP_TEST_EVAL $name"
  else
    CUDA_VISIBLE_DEVICES=$gpu "$PYTHON_BIN" -m jdcnet_exp.evaluate \
      --config "$test_cfg" --checkpoint "$run_dir/best.pt" \
      --output-dir "$run_dir/test_eval" \
      >> "$log_f" 2>&1
    log "DONE_TEST_EVAL $name"
  fi
}
FUNC
    echo 'export -f run_one log done_run done_test_eval'
    echo "export CONFIG_DIR='$CONFIG_DIR' RUN_ROOT='$RUN_ROOT' LOG_DIR='$LOG_DIR' STATUS='$STATUS' PYTHON_BIN='$PYTHON_BIN'"
    echo "cat '$qfile' | xargs -I{} -P $CONCURRENCY bash -c 'run_one $gpu \"\$@\"' _ {}"
    echo "log 'GPU_EXT_DONE gpu=$gpu'"
  } > "$script"
  chmod +x "$script"

  screen_name="drr_ext_g${gpu}"
  screen -S "$screen_name" -X quit >/dev/null 2>&1 || true
  screen -dmS "$screen_name" bash -c \
    "bash '$script' > '$LOG_DIR/gpu${gpu}_ext_queue.log' 2>&1"
  log "LAUNCHED_EXT gpu=$gpu screen=$screen_name runs=${#assigned[@]}"
done

log "EXT_ALL_LAUNCHED total=$NUM_RUNS"
screen -ls 2>/dev/null | grep drr_ext || true
